# docker-compose.yml
version: '3.9'

services:
  backend:
    build: .
    command: >
      sh -c "
      if [ '$$ENVIRONMENT' = 'dev' ] ; then
        uvicorn app.main:app --reload --host 0.0.0.0 --port $$FASTAPI_PORT;
      else
        uvicorn app.main:app --host 0.0.0.0 --port $$FASTAPI_PORT;
      fi"
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    networks:
      - docker_net
    volumes:
      - .:/app
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'
    environment:
      DB_UPSTREAM: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:6000

  frontend:
    stdin_open: true
    build:
      context: ./frontend
      args:
        HOST: ${HOST}
        FASTAPI_PORT: ${FASTAPI_PORT}
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - 80:80
    networks:
      - docker_net
    logging:
      driver: 'json-file'
      options:
        max-size: '1k'
        max-file: '3'
networks:
  docker_net: